<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图信息"
            }

            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"出租房管理",
                        "menuJump":"列表",
                        "tableName":"chuzufang"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改"
                        ],
                        "menu":"出租房留言管理",
                        "menuJump":"列表",
                        "tableName":"chuzufangLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"出租房收藏管理",
                        "menuJump":"列表",
                        "tableName":"chuzufangCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"出租房订单管理",
                        "menuJump":"列表",
                        "tableName":"chuzufangOrder"
                    }
                ],
                "menu":"出租房管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"出租房类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryChuzufang"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"时间段管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryShijianduan"
                    }

                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"用户管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"用户管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"出租房管理",
                        "menuJump":"列表",
                        "tableName":"chuzufang"
                    }
                ],
                "menu":"出租房管理"
            }
			,
			{
                "child":[
                    
                    {
                        "buttons":[
                            "查看",
                            "修改"
                        ],
                        "menu":"出租房留言管理",
                        "menuJump":"列表",
                        "tableName":"chuzufangLiuyan"
                    }
                ],
                "menu":"出租房留言管理"
            }
			,
			{
                "child":[
                    
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"出租房收藏管理",
                        "menuJump":"列表",
                        "tableName":"chuzufangCollection"
                    }
                ],
                "menu":"出租房收藏管理"
            }
			,
			{
                "child":[
                    
                    {
                        "buttons":[
                            "查看",
                            "审核"
                        ],
                        "menu":"出租房订单管理",
                        "menuJump":"列表",
                        "tableName":"chuzufangOrder"
                    }
                ],
                "menu":"出租房订单管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"用户",
        "tableName":"yonghu"
    }
];

var hasMessage = '';
